[package]
name = "w002_prime100"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winsafe = { version = "0.0.18", features = ["shell"] }
num-bigint = "0.4"